### ISSUE TITLE
basemap default not working

### ISSUE THREAD

**Issue by nealhaddaway** [mjwestgate/eviatlas#14]
The default basemap no longer displays in the downloaded HTML

**Comment by DrMattG** [comment]
I can get it to work for all BUT "openStreetMap" basemap. Does it work the same for you?

**Comment by nealhaddaway** [comment]
Yeah exactly.
________________________________

**Comment by DrMattG** [comment]
Okay - first it looks like this was fixed recently by Leaflet (https://github.com/rstudio/leaflet/issues/786). So the users need to re-install leaflet. I have not managed to fix it in the app yet but this works: 

` library(leaflet)
library(htmlwidgets)
library(leaflet.providers)

m <- leaflet(data.frame(lat = 55.71654, lng = 12.47484))
m <-  addCircles(m, popup = "testpopup")
#m <-m %>% addTiles()
m<-m %>% addProviderTiles(provider = providers$OpenStreetMap)
m
saveWidget(m, file="testmap.html")

`
Perhaps if the user chooses openstreetmap as the base we can have an ifelse statement to go to addTiles()?

**Comment by DrMattG** [comment]
Added pull request : https://github.com/ESHackathon/eviatlas/pull/69 Can you review and see if it works! (it works locally for me now but I had to reinstall leaflet first before eviatlas)

**Comment by nealhaddaway** [comment]
Yeah this works for me now! Just trying to work out how to deploy to shinyapps.io
